### ISSUE TITLE
关于课程表重新加载课程的问题

### ISSUE THREAD

**Issue by isnine** [GanWenPeng/GWPCourseListView#1]
我非常喜欢这个课程表，但在学习过程中，遇到了一个问题，一直无法解决。
所以想向你请教一下，在界面打开的时候(NSArray<CourseModel *> *)courseArr这个方法会设置课程表的课程数据。
但是我想实现一个点击按钮，然后重新加载一遍课程表数据以达到添加课程或者更换课程表的目的，不知道该执行那个方法。

**Comment by gwpp** [comment]
谢谢你的使用，随手做的一个小东西没有维护过，没想到有人会用到，不好意思。看了你的问题我对这个课程表做了一点完善，请下载最新的GWPCourseListView代码，里面增加了reloadData方法可以实现你的刷新需求。同时增加了几个用于控制显示样式的代理方法，希望对你有所帮助。具体使用请参考demo

**Comment by isnine** [comment]
十分感谢，这些对我十分有用.因为我才看到信息，并且也才学IOS半个月不到，所以这几天我用了很多很笨的方法来解决。
添加课程这个问题，我用了switch()来根据课程数目多少，然后case里面就return相应的课程数目。
我同时还遇到了一个加载的问题，我发现课程加载顺序必须先加载前一节才能再加载后一节的，举例

``` c
        CourseModel *a = [CourseModel courseWithName:@"Java" dayIndex:1 startCourseIndex:1 endCourseIndex:2];
        CourseModel *b = [CourseModel courseWithName:@"C++" dayIndex:1 startCourseIndex:3 endCourseIndex:4];
        CourseModel *c = [CourseModel courseWithName:@"C#" dayIndex:1 startCourseIndex:5 endCourseIndex:6];
        _courseArr = [NSMutableArray arrayWithArray:@[a,b,c]];
```

这样是可以的  但是如果将最后一行改为

```
_courseArr = [NSMutableArray arrayWithArray:@[a,c,b]];
```

将会显示错误，这个Bug我依旧利用了大量if判断的笨方法排序后规避掉了。

最后还想请教一个问题，我希望点能New按钮后，做到的不仅仅只是添加一个课程，希望能够重新刷新一遍课程数据,(实际使用场景就是按一下按钮显示下一周的数据)，我自己有尝试解决这个问题，但是因为基础薄弱，依旧是采用很笨很笨的方法，就是点下按钮将这个界面退出后再重新打开(惭愧~~)

**Comment by isnine** [comment]
感谢，我已经用reloadData方法，发现可以加载了，谢谢你的帮助。
同时我将实际使用效果加在README中并且修改了一些细节bug已经Pull给你了。

**Comment by gwpp** [comment]
OK，3Q
